[build]
command = "true"
publish = "."

[[redirects]]
from = "http://curio.sh/*"
to = "https://docs.bearer.com/:splat"
status = 301
force = true

[[redirects]]
from = "https://curio.sh/*"
to = "https://docs.bearer.com/:splat"
status = 301
force = true

[[redirects]]
from = "http://docs.bearer.sh/*"
to = "https://docs.bearer.com/:splat"
status = 301
force = true

[[redirects]]
from = "https://docs.bearer.sh/*"
to = "https://docs.bearer.com/:splat"
status = 301
force = true
